// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABUJN0DJjtTVnbGuM1Pjf_wkbqq55k7lw',
    appId: '1:701288295703:web:490cfe34c5a87b4d641b52',
    messagingSenderId: '701288295703',
    projectId: 'ponto-flutter-apk',
    authDomain: 'ponto-flutter-apk.firebaseapp.com',
    storageBucket: 'ponto-flutter-apk.firebasestorage.app',
    measurementId: 'G-LDHKMMF3MD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIoNhEwPGQ9Y8nvDFL7coRXiE6GuNEXxI',
    appId: '1:701288295703:android:9d9759fbbd4302e7641b52',
    messagingSenderId: '701288295703',
    projectId: 'ponto-flutter-apk',
    storageBucket: 'ponto-flutter-apk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBJXZi_xKCUTwdzMJumQSqSfFNJxxX7JQ',
    appId: '1:701288295703:ios:bebed8ef0139acea641b52',
    messagingSenderId: '701288295703',
    projectId: 'ponto-flutter-apk',
    storageBucket: 'ponto-flutter-apk.firebasestorage.app',
    iosBundleId: 'com.example.controlePonto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBJXZi_xKCUTwdzMJumQSqSfFNJxxX7JQ',
    appId: '1:701288295703:ios:bebed8ef0139acea641b52',
    messagingSenderId: '701288295703',
    projectId: 'ponto-flutter-apk',
    storageBucket: 'ponto-flutter-apk.firebasestorage.app',
    iosBundleId: 'com.example.controlePonto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABUJN0DJjtTVnbGuM1Pjf_wkbqq55k7lw',
    appId: '1:701288295703:web:490cfe34c5a87b4d641b52',
    messagingSenderId: '701288295703',
    projectId: 'ponto-flutter-apk',
    authDomain: 'ponto-flutter-apk.firebaseapp.com',
    storageBucket: 'ponto-flutter-apk.firebasestorage.app',
    measurementId: 'G-LDHKMMF3MD',
  );
}
